### PR TITLE
OISP: Implementing the e2e testing framework

### PR DESCRIPTION
**Pull request by jelyoussefi**
The e2e testing framework is ready to be merged

### CODE REVIEW

**Comment by nevets963** [comment]
This PR will also need to be approved at the same time: https://github.com/emea-ssg-drd/iotanalytics-dashboard/pull/32

**Comment by nevets963** [comment]
This PR also needs to approved: https://github.com/emea-ssg-drd/iotanalytics-websocket-server/pull/7

**Comment by nevets963** [comment]
@wagmarcel Me and Jamal have contributed to the e2e test suite. Can you review our code?

**Comment by wagmarcel** [comment]
Also, please check the headers. They show BSD licence but for this repository we have Apache 2.0 licence.

**Pull request merged**
